baseURL = "https://teeramaet.github.io/"
languageCode = "en-us"
title = "0x0nigiri"
theme="archie"
copyright = "© 0x0nigiri"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[pagination]
  pagerSize = 3 # articles per page

[params]
	mode = "light" # color-mode → light,dark,toggle or auto
	useCDN = false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "CTF writeups and cybersecurity articles made by noob"
	mathjax = false # enable MathJax support
	katex = true # enable KaTeX support
	customcss = ["css/color.css"]
# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/teeramaet"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://x.com/0x0nigiri"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/teeramaet-bongkodmalee-35213a263"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[caches]
	[caches.images]
		dir = ':cacheDir/images'